// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ums_dotnet.DbContexts;

#nullable disable

namespace ums_dotnet.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220707190241_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ums_dotnet.Entities.Authority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Authority");
                });

            modelBuilder.Entity("ums_dotnet.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "johnny@depp.com",
                            FirstName = "Johnny",
                            LastName = "Depp",
                            Password = "johnny123",
                            Status = "Active",
                            UserName = "John1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jimm@carrey.com",
                            FirstName = "Jimm",
                            LastName = "Carrey",
                            Password = "Jimm123",
                            Status = "Active",
                            UserName = "Jimm1"
                        },
                        new
                        {
                            Id = 3,
                            Email = "angelina@jolie.com",
                            FirstName = "Angelina",
                            LastName = "Jolie",
                            Password = "angelina123",
                            Status = "Active",
                            UserName = "Angelina1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "dwayne@johnson.com",
                            FirstName = "Dwayne",
                            LastName = "Johnson",
                            Password = "dwayne123",
                            Status = "Active",
                            UserName = "Dwayne1"
                        },
                        new
                        {
                            Id = 5,
                            Email = "tom@hanks.com",
                            FirstName = "Tom",
                            LastName = "Hanks",
                            Password = "tom123",
                            Status = "Active",
                            UserName = "Tom1"
                        },
                        new
                        {
                            Id = 6,
                            Email = "tom@cruise.com",
                            FirstName = "Tom",
                            LastName = "Cruise",
                            Password = "tom123",
                            Status = "Active",
                            UserName = "Tom1"
                        },
                        new
                        {
                            Id = 7,
                            Email = "monica@belucci.com",
                            FirstName = "Monica",
                            LastName = "Belucci",
                            Password = "belucci123",
                            Status = "Inactive",
                            UserName = "Monica1"
                        },
                        new
                        {
                            Id = 8,
                            Email = "anthony@hopkins.com",
                            FirstName = "Anthony",
                            LastName = "Hopkins",
                            Password = "anthony123",
                            Status = "Inactive",
                            UserName = "Anthony1"
                        },
                        new
                        {
                            Id = 9,
                            Email = "jack@nicholson.com",
                            FirstName = "Jack",
                            LastName = "Nicholson",
                            Password = "jack123",
                            Status = "Inactive",
                            UserName = "Jack1"
                        },
                        new
                        {
                            Id = 10,
                            Email = "al@pacino.com",
                            FirstName = "Al",
                            LastName = "Pacino",
                            Password = "al123",
                            Status = "Active",
                            UserName = "Al1"
                        },
                        new
                        {
                            Id = 11,
                            Email = "dustin@hoffman.com",
                            FirstName = "Dustin",
                            LastName = "Hoffman",
                            Password = "dustin123",
                            Status = "Active",
                            UserName = "Dustin1"
                        },
                        new
                        {
                            Id = 12,
                            Email = "danzel@washington.com",
                            FirstName = "Denzel",
                            LastName = "Washington",
                            Password = "danzel123",
                            Status = "Active",
                            UserName = "Danzel1"
                        },
                        new
                        {
                            Id = 13,
                            Email = "robin@williams.com",
                            FirstName = "Robin",
                            LastName = "Williams",
                            Password = "robin123",
                            Status = "Active",
                            UserName = "Robin1"
                        },
                        new
                        {
                            Id = 14,
                            Email = "morgan@freeman.com",
                            FirstName = "Morgan",
                            LastName = "Freeman",
                            Password = "morgan123",
                            Status = "Active",
                            UserName = "Morgan1"
                        },
                        new
                        {
                            Id = 15,
                            Email = "gene@hackman.com",
                            FirstName = "Gene",
                            LastName = "Hackman",
                            Password = "gene123",
                            Status = "Inactive",
                            UserName = "Gene1"
                        });
                });

            modelBuilder.Entity("ums_dotnet.Entities.Authority", b =>
                {
                    b.HasOne("ums_dotnet.Entities.User", null)
                        .WithMany("Authority")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ums_dotnet.Entities.User", b =>
                {
                    b.Navigation("Authority");
                });
#pragma warning restore 612, 618
        }
    }
}
